include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_final_fields
    - avoid_print
    - avoid_empty_else
    - no_duplicate_case_values
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - empty_catches
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - use_rethrow_when_possible
